server:
  port: 5050

booklay:
  shop-origin: http://localhost:9090/

  # Redis
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password:

token:
  expiration_time: 86400000
  secret: booklay_token
