server:
  port: 5050

booklay:
  shop-origin: http://125.6.38.201:9090/

  # Redis
  redis:
    host: 133.186.151.141
    port: 6379
    database: 4
    password: "*N2vya7H@muDTwdNMR!"

token:
  expiration_time: 86400000
  secret: booklay_token
